apiVersion: v1
kind: Service
metadata:
  name: ext-authz
  labels:
    app: ext-authz
    service: ext-authz
spec:
  ports:
  - port: 5005
    name: tcp
  selector:
    app: ext-authz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-authz
  labels:
    app: ext-authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz
  template:
    metadata:
      labels:
        app: ext-authz
    spec:
      containers:
      - name: ext-authz
        image: ext-authz
        imagePullPolicy: Never
        ports:
        - containerPort: 5005
